server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/database"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "1Ln55lu2teW6wbb2nd3sLkHUQgql0e/avY0TCtXgEkERCDXm6tB6m64jXVXf43jn"
  valid-duration: 10  # second
  refreshable-duration: 120 # second

supabase:
  url: "https://qtlwqfhffuffjcgkgity.supabase.co"
  key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0bHdxZmhmZnVmZmpjZ2tnaXR5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MDAyNjI5NCwiZXhwIjoyMDU1NjAyMjk0fQ.sRVChWMFDxUiHZcsAbaORZ84gLP3eJ47GTDdrQFYGN4"
  bucket: "ImageBucket"